In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3], [4,5,6],[7,8,9]]

In [9]:
mat=np.array(my_mat)

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.29622906, 0.34676067, 0.25773671, 0.88086115, 0.18473957])

In [22]:
np.random.rand(5,5)

array([[0.08263527, 0.82744723, 0.44436613, 0.73795738, 0.83208533],
       [0.48584146, 0.80334076, 0.81598118, 0.96971945, 0.45050435],
       [0.29746057, 0.47610014, 0.99703321, 0.04357984, 0.63952742],
       [0.51152606, 0.32727713, 0.36853453, 0.31400746, 0.5764663 ],
       [0.95555384, 0.88234558, 0.62166048, 0.36039502, 0.71381067]])

In [23]:
np.random.randn(4)

array([ 1.34074799, -1.18472792, -0.82960596, -0.41817355])

In [24]:
np.random.randn(4,4)

array([[ 0.21532324, -0.31465679, -0.737328  , -1.22512498],
       [ 0.07307552, -1.00258954, -0.95949557,  0.4476721 ],
       [ 0.48198065,  0.08882627, -0.48537157, -0.38202014],
       [ 0.35613459,  0.58645047,  0.15606092,  0.19875124]])

In [27]:
np.random.randint(1,100)

15

In [28]:
np.random.randint(1,100,10)

array([30, 67, 16, 45, 25, 33, 78, 15, 69, 34])

In [29]:
arr=np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
randarr=np.random.randint(0,50,10)

In [32]:
randarr

array([38, 22, 24, 25, 34, 12,  9,  5, 24, 28])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
randarr.max()

38

In [36]:
randarr.min()

5

In [38]:
arr.shape

(25,)

In [39]:
randarr.shape

(10,)

In [40]:
arr1=arr.reshape(5,5)
arr1.shape

(5, 5)