In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[9]

9

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
slice_arr=arr[0:6]

In [9]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_arr[:]=99

In [12]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr1=arr.copy()

In [15]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr1[0:4]=10

In [17]:
arr1

array([10, 10, 10, 10, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d=np.array([[5,10,15], [20,25,30], [30,35,40]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [24]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[0][2]

15

In [26]:
arr_2d[0,2]

15

In [27]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[1:]

array([[20, 25, 30],
       [30, 35, 40]])

In [30]:
arr_2d[1:, 0:1]

array([[20],
       [30]])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr > 10

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [33]:
arr[arr>10]

array([99, 99, 99, 99, 99, 99])

In [34]:
arr[arr<10]

array([6, 7, 8, 9])

In [36]:
arr[arr==10]

array([10])